apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-ssh-key
  labels:
{{ include "openmpi.labels" . | indent 4 }}
data:
  id_rsa: {{ .Values.sshKey.id_rsa | b64enc | quote }}
  id_rsa.pub: {{ .Values.sshKey.id_rsa_pub | b64enc | quote }}
  authorized_keys: {{ .Values.sshKey.id_rsa_pub | b64enc | quote }}
