# Declare variables to be passed into your templates.

replicaCount: 2

image:
  repository: everpeace/kube-openmpi
  tag: 0.7.0
  pullPolicy: Always

sshKey:
  id_rsa: |
    -----BEGIN OPENSSH PRIVATE KEY-----
    b3BlbnNzaC1rZXktdjEAAAAABG5vbmUAAAAEbm9uZQAAAAAAAAABAAACFwAAAAdzc2gtcn
    NhAAAAAwEAAQAAAgEAyE/u9q5T8bC1D4KYfL2siM7x1Xg5uiHm8CgBnIN5w1HeR4m62aMp
    lCnfkEx+hS8qfjLeEepZEO5HSlrvO26tlPy111G0g2i0RPsorv4qR2T17gJylIqRD2WVLd
    KAMwwAvrZRbloaSh8sQesZLUsrN5UMVcB0/V/dRDPUYVmriZArzGxdH9HxjQeK6WgSkYiR
    dEEVXuhJfKvC+eM88ukhGB+d8JTYCREtKDWpo3TeWfXSg+yl2I5DVt9wWyKchrt9hD1tiK
    drBnNm67MHyzHbo+V4Mrzvsz7yuKCfkVyZuSTNtx0zdVY6FCrEUuW5OvvldqdtemXkqxSk
    7bvoYjJkTnWfxu37bL4WQEFkkKWFSorl3WegO3krNZhWKd/POuGpZfo0/poY3frAfM0m2e
    a8AX3RphavMMoa3iVrVn9z56k8bLSRU9GM4ahu4Uh7DP4J48I8BvNqQinIR7/TlXpeAbH8
    45hOKBr6JPkVrhoSk97p10cU3MGfYLb0zVHPdhqhMNwsuGOS7qil0UHj91PBP5SQVZS+Vf
    v61p/sduaBG25jCr6p3MU7m0jUpnOWpRhRUyBsGBdwQq/kVI9KaWw0lBy24oDMhhxcS8ZX
    Rg/PO7i87XR0oyE0c32o4zgn4rcD8FfUy17p6sjgQwYge5qzcJxA8kqaYOtgggCd+AjsKo
    kAAAdQGhsNOBobDTgAAAAHc3NoLXJzYQAAAgEAyE/u9q5T8bC1D4KYfL2siM7x1Xg5uiHm
    8CgBnIN5w1HeR4m62aMplCnfkEx+hS8qfjLeEepZEO5HSlrvO26tlPy111G0g2i0RPsorv
    4qR2T17gJylIqRD2WVLdKAMwwAvrZRbloaSh8sQesZLUsrN5UMVcB0/V/dRDPUYVmriZAr
    zGxdH9HxjQeK6WgSkYiRdEEVXuhJfKvC+eM88ukhGB+d8JTYCREtKDWpo3TeWfXSg+yl2I
    5DVt9wWyKchrt9hD1tiKdrBnNm67MHyzHbo+V4Mrzvsz7yuKCfkVyZuSTNtx0zdVY6FCrE
    UuW5OvvldqdtemXkqxSk7bvoYjJkTnWfxu37bL4WQEFkkKWFSorl3WegO3krNZhWKd/POu
    GpZfo0/poY3frAfM0m2ea8AX3RphavMMoa3iVrVn9z56k8bLSRU9GM4ahu4Uh7DP4J48I8
    BvNqQinIR7/TlXpeAbH845hOKBr6JPkVrhoSk97p10cU3MGfYLb0zVHPdhqhMNwsuGOS7q
    il0UHj91PBP5SQVZS+Vfv61p/sduaBG25jCr6p3MU7m0jUpnOWpRhRUyBsGBdwQq/kVI9K
    aWw0lBy24oDMhhxcS8ZXRg/PO7i87XR0oyE0c32o4zgn4rcD8FfUy17p6sjgQwYge5qzcJ
    xA8kqaYOtgggCd+AjsKokAAAADAQABAAACADzvE+I2ZZLADlQJhhlsGXAEg8xMJkNYzMeB
    Y/wYgpHH9bYNT6mk2KEZm8hpfJNHJcX980+/2hgsY8NapiuOH3+S4D3/vMm8sBnLzTRuXK
    4bKDSeyfwlqrrkS90Ei7r7i7539416G0Uw9mWW/rGojBz8WiQ7x1rMLqLwoUp73JKcKLam
    wC1N0Az2nmsiHYPn51dV9QpJ3xDtrwIU/hVmlYqhE4p7vLwFXZc9u7zdcEYtYTyAYHLf09
    w5XBRdEwBpSGVRymAnjYcI0+YfL9+/6vCQfV/x2XjNTUick+3EHX8Ukv+BAoZPFJvN5qrQ
    9ufaeJL/m24AUO85+HHZF3fHnHs3nchFAvQjcp+X93YxqvubuxHnoYA1PfeaFubEr+1WpU
    IzRUCo2pzbktAgVRQ4V0i6LSxkBBh/nmuOKPVqJBA8MT4fT9Y6wPY19h72B+zZ80FCQvDs
    +5JTt99PdPdwNPRPrGxdVr+hGhij5Rvu8gY9PHWT7PRuZPECx3bbaM8aWK3uOmAMwTw9fp
    VV7hWqBe+q5Mbyqpj03MWc8YWSBTPjaD6MjoET5Xp0c3dX9oudBhn6JndpGz0HY4ncDuvf
    jtv5L3ShQ+pWKIbUQH86d9g72/iNFZUf5i9JEOec8GuG3bWiuZJiZpxQN4R8VBDaB9NL31
    SvP1eWBGh+6nAaz6+BAAABAD0F18D1JlPtofwOcNOaIb7gafmvYSeFJsQ2dAxACmGeJHMu
    cr5coQBKBN3EqyKP4DbDmVR02gHxgvnltmtKZ6OQABGceoDKXJEWWfLu/h9PPco9zN3tco
    GXDxEKa/Q92wvUv0nbbSLvz02DNU90lg5sZ9PYlo7cDC59T0ubmuzdtghprf7K2Mm6Bzxi
    0g2LbmBrhsUYPFjjFCM1dBCfA6xiHvRbhzuRTmCd2Rbq6r0jXYHNdvcUFzyGXsR7ak7Qoo
    eh3JnTO0XvjFS284tfmhlX4Y5vl7KG9/XG4ALk3oouG501BpHTLtJWH6C1vJEiD6vEUh6/
    vfKcxRvPRTOdWbQAAAEBAO2sxBiQVGUPCxmwcna63c7bWkmIoz5b0U7ly6jlEotmLcWQ+K
    RpnZjnVnKZQoX7flqOjC+NNX3K9KdgubvuCmasz3/6Ogsbi4lYnTage+gBEILg01J/4/za
    XiVmpsiqoC206T5ecnnyR30I1fZYDY+DHQmoMXkxVg2sqV1mDe6cL8eGpYusVr7oXdv12E
    8XTQ/sd8JHuv2j9fc2U1N9315is/2K6z1fFoj93q52CDJSUnQN39TOpYf15qhbUuM2grrm
    OL2X/zTTflxHoaMBx96XCOEqkEhwcSiCZ/PnYMCPAPbxmOtJBlpJ9Ni6CtAPXXofrMHzpw
    QOKWQaVszp5KsAAAEBANfBs+bxjWBWeaRTXv13P9vNHFqojAVqJElAsN10Z4iQ+W576JqF
    rP1iPsNFAaHwk1mh8C4CYs0LjoTDemmdxQNC2JNVE+Losd88n4w3zrMAqxzJFJsAkO7ADn
    3P39Wzu9vL7rhoJYCmJdTWMd9WZnlHqtNgO/wVs9vrxCy2HO8arSpSEElL+VDyN41Vhdkp
    0qlcI2BqIPVuXuP/P+HFHE++KA3LWkh/Dnvb+IWrC5gbD3aIUYl66LsIGG/cfri56dS5eX
    iDr0AMvqmoqdTg77IHok1AmB5FQJiJtXBSeq2bMfDsYIae2rAUML9e3/fvgw9mTFUHnUa0
    kusqrefGJZsAAAAaZ2xhc3NvZndoaXNrZXlAdGhlLW1hY2hpbmUB
    -----END OPENSSH PRIVATE KEY-----
  id_rsa_pub: |
    ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDIT+72rlPxsLUPgph8vayIzvHVeDm6IebwKAGcg3nDUd5HibrZoymUKd+QTH6FLyp+Mt4R6lkQ7kdKWu87bq2U/LXXUbSDaLRE+yiu/ipHZPXuAnKUipEPZZUt0oAzDAC+tlFuWhpKHyxB6xktSys3lQxVwHT9X91EM9RhWauJkCvMbF0f0fGNB4rpaBKRiJF0QRVe6El8q8L54zzy6SEYH53wlNgJES0oNamjdN5Z9dKD7KXYjkNW33BbIpyGu32EPW2Ip2sGc2brswfLMduj5XgyvO+zPvK4oJ+RXJm5JM23HTN1VjoUKsRS5bk6++V2p216ZeSrFKTtu+hiMmROdZ/G7ftsvhZAQWSQpYVKiuXdZ6A7eSs1mFYp38864all+jT+mhjd+sB8zSbZ5rwBfdGmFq8wyhreJWtWf3PnqTxstJFT0YzhqG7hSHsM/gnjwjwG82pCKchHv9OVel4BsfzjmE4oGvok+RWuGhKT3unXRxTcwZ9gtvTNUc92GqEw3Cy4Y5LuqKXRQeP3U8E/lJBVlL5V+/rWn+x25oEbbmMKvqncxTubSNSmc5alGFFTIGwYF3BCr+RUj0ppbDSUHLbigMyGHFxLxldGD887uLztdHSjITRzfajjOCfitwPwV9TLXunqyOBDBiB7mrNwnEDySppg62CCAJ34COwqiQ== streamflow@mpi

nameOverride: ""
fullnameOverride: ""
