name: "CI Tests"
on:
  push:
    branches:
      - master
      - debug/blurb
  pull_request:
    branches:
      - master
concurrency:
  group: build-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true
jobs:
  static-checks:
    name: "StreamFlow static checks"
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        step: [ "lint" ]
    env:
      TOXENV: ${{ matrix.step }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.13"
          cache: pip
          cache-dependency-path: |
            requirements.txt
            test-requirements.txt
            tox.ini
      - name: "Install Python Dependencies and StreamFlow"
        run: |
          python -m pip install tox --user
          python -m pip install . --user
      - name: "Run StreamFlow static analysis via Tox"
        run: tox
  blurb:
    name: "StreamFlow blurb tests"
    strategy:
      matrix:
        on: [ "ubuntu-24.04"]
        python: [ "3.9", "3.10", "3.11", "3.12", "3.13" ]
        retries: ["1", "2", "3", "4", "5"]
    runs-on: ${{ matrix.on }}
    env:
      VERSION: "v1.2"
      COMMIT: "main"
      REPO: "cwl-v1.2"
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python }}
          cache: pip
          cache-dependency-path: |
            requirements.txt
            tox.ini
      - uses: actions/setup-node@v4
        with:
          node-version: "20"
      - uses: docker/setup-qemu-action@v3
        if: ${{ startsWith(matrix.on, 'ubuntu-') }}
      - name: "Install Python Dependencies and StreamFlow"
        run: |
          python -m pip install tox --user
          python -m pip install . --user
      - name: "Download CWL tests"
        run: |
          wget "https://github.com/common-workflow-language/${REPO}/archive/${COMMIT}.tar.gz"
          tar xzf "${COMMIT}.tar.gz"
      - name: "Run blurb"
        run: |
          cd ${REPO}-${COMMIT}
          cwl-runner --version
          cwl-runner tests/inpdir_update_wf.cwl tests/empty.json --debug