name: "StreamFlow Tests"
on:
  workflow_run:
    workflows:
      - "CWL Conformance"
    branches:
      - master
    types:
      - completed
jobs:
  test:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: "3.8"
      - uses: actions/setup-node@v2
        with:
          node-version: "15"
      - uses: docker/setup-qemu-action@v1
      - uses: docker/setup-buildx-action@v1
      - name: "Install Python Dependencies and Streamflow"
        run: |
          python -m pip install requests tabulate pytest pytest-asyncio --user
          python -m pip install . --user
      - name: "Run StreamFlow tests (excluding CWL Conformance)"
        run: pytest -m "not conformance"
